---
title: ""
format:
  html:
    code-link: true
    toc: true
    css: styles.css
execute:
  echo: true
editor_options: 
  markdown: 
    wrap: 80
engine: knitr
---

## Overview

Currently, my research agenda fits into two broad buckets:

1.  The socio-political effects of interacting with local political institutions in the US, focusing on [**police departments**]{style="color:teal"} and [**public housing authorities**]{style="color:teal"}.
2.  How [**emerging technologies**]{style="color:teal"} change the way people experience and perceive the state.

At the intersection of this, I am interested in questions like: How do technology companies influence local policymaking and biases in public service provision? Where and why do local officials implement AAI-assisted policies like ShotSpotter in policing and Landlord Tech in housing? And, how do these tools shape political trust and civic engagement in marginalized communities?

::: {.callout-tip appearance="minimal"}
I have provided pdfs of my work below. Where possible, I have also added an ["In The Wild"]{style="color:teal"} button, which links to examples of this work's impact outside the ivory tower, including in testimonials and policy reports.
:::

## Conference Papers

Gupta, A., Wu, V., **Webley-Brown, H**., King, J., Ho, D. (2023). [The Privacy-Bias Tradeoff: Data Minimization and Racial Disparity Assessments in U.S. Government](https://dl.acm.org/doi/10.1145/3593013.3594015). In Proceedings of the 2023 ACM Conference on Fairness, Accountability, and Transparency (FAccT '23).

::: {.callout-note collapse="true" icon=false}

## <i class="bi bi-lightning"></i> &nbsp; Abstract

An emerging concern in algorithmic fairness is the tension with privacy interests. Data minimization can restrict access to protected attributes, such as race and ethnicity, for bias assessment and mitigation. Less recognized is that for nearly 50 years, the federal government has been engaged in a large-scale experiment in data minimization, limiting (a) data sharing across federal agencies under the Privacy Act of 1974, and (b) data collection under the Paperwork Reduction Act. We document how this “privacy-bias tradeoff” has become an important battleground for fairness assessments in the U.S. government and provides rich lessons for resolving these tradeoffs. President Biden’s 2021 racial justice Executive Order 13,985 mandated that federal agencies conduct equity impact assessments (e.g., for racial disparities) of federal programs. We conduct a comprehensive assessment across high-volume claims agencies that affect many individuals, as well as all agencies filing “equity action plans,” with three findings. First, there is broad agreement in principle that equity impact assessments are important, with few parties raising privacy challenges in theory and many agencies proposing substantial efforts. Second, in practice, major agencies do not collect and may be affirmatively prohibited under the Privacy Act from linking demographic information. This has led to pathological results: until 2022, for instance, the US Dept. of Agriculture imputed race by “visual observation” when race information was not collected. Data minimization has meant that even where agencies want to acquire demographic information in principle, the legal, data infrastructure, and bureaucratic hurdles are severe. Third, we derive policy implications to address these barriers.

:::

::: {.callout-caution collapse="true" icon=false}

## <i class="bi bi-trophy"></i> &nbsp; Recognition

- [Best Paper Award](https://facctconference.org/2023/acceptedpapers) – FAccT 2023
- [Student Paper Award](https://fpf.org/wp-content/uploads/2024/02/FPF-PPPM-2024-Digest-FINAL-PRINT-R3-singles-1.pdf) – Privacy Papers for Policymakers (PPPM) by the Future of Privacy Forum
:::

<a href="papers/privacy-bias-tradeoff.pdf" target="_blank" rel="noopener noreferrer" class="bi-file-earmark-pdf-fill btn btn-danger" role="button"> pdf</a>
<a href="https://hai.stanford.edu/policy/policy-brief-privacy-bias-trade" target="_blank" rel="noopener noreferrer" class="bi-bank btn btn-success" role="button"> Policy Brief</a>
<a href="papers/upturn-omb_testimony-HSGAC.pdf" target="_blank" rel="noopener noreferrer" class="bi-geo-alt btn btn-primary" role="button"> In The Wild </a>


## Works in Progress

We’ve Got Democracy at Home: Resident Council Emergence in Public Housing Developments.

Don’t Shoot The Messenger: Do Open Data Initiatives Moderate the Effect of Police Violence News on Trust in Police?

Why Watch The Watchers? Frame Utilization In Community Control Over Police Surveillance (CCOPS) Legislation and Media Coverage.


## Research Reports

__Webley-Brown, H.__, Sipek, A., Buoymaster, K., Shivalkar, J., Owen, W., Manis, E. (2022). [ShotSpotter and the Misfires of Gunshot Detection Technology](https://www.stopspying.org/shotspotter). Surveillance Technology Oversight Project.

<a href="papers/shotspotter.pdf" target="_blank" rel="noopener noreferrer" class="bi-file-earmark-pdf-fill btn btn-danger" role="button"> pdf</a>
<a href="papers/epic-doj.pdf" target="_blank" rel="noopener noreferrer" class="bi-geo-alt btn btn-primary" role="button"> In The Wild </a>

<hr>

 Loshkajian, N., Van Doran, S., Melendi, J., Saran, S., __Webley-Brown, H.__, Manis, E. (2022). [Privatizing The Surveillance State: How Police Foundations Undermine Rule of Law](https://www.stopspying.org/privatizing-surveillance-state). Surveillance Technology Oversight Project.

<a href="papers/privatizing-surveillance-state.pdf" target="_blank" rel="noopener noreferrer" class="bi-file-earmark-pdf-fill btn btn-danger" role="button"> pdf</a>

<hr>

__Webley-Brown, H__. (2021). False Freedom: Exploring Clients’ Pretrial Experiences on Electronic Monitors. The Bail Project.

<a href="papers/false-freedom.pdf" target="_blank" rel="noopener noreferrer" class="bi-file-earmark-pdf-fill btn btn-danger" role="button"> pdf</a>
<a href="papers/san-fran-em.pdf" target="_blank" rel="noopener noreferrer" class="bi-geo-alt btn btn-primary" role="button"> In The Wild </a>

