---
title: ""
format:
  html:
    code-link: true
    toc: true
    css: styles.css
execute:
  echo: true
editor_options: 
  markdown: 
    wrap: 80
engine: knitr
---

## Overview

::: {.callout-tip appearance="minimal"}
Even though I've been through two application cycles now and have some graduate training under my belt, there's still a ton of things I don't know, but I'm always happy to talk with people who are considering applying to graduate school or are already in a program (and maybe even considering leaving one like I did). 

On this page, I've shared two types of resources. First, I've provided previous [application materials](resources.html#application-materials), specifically the CV, SOP, and PS that I submitted. Second, I've made suggested [reading lists](resources.html#reading-suggestions) featuring several scholars' insights into navigating academia. These resources have helped me along the way and I hope they prove helpful to others.
:::

There's a hidden curriculum that structures much of academic life. If you're not "in the know," you can lose out on various funding, mentorship, and learning opportunities. If you're "in the know," it is easier to overlook that things remains hidden to others and the advantages that played a role in them becoming unhidden to you. 

"I don't even know what I don't know" has been a constant thought reverberating in my head throughout grad school. When I first started my Ph.D. (the first time around), I felt like I'd jumped out of a plane and been told to build a parachute on the way down. This challenge was exciting and the learning curve---while steep---was transformative. But, I started to look around and saw that some people had been given a high quality parachute before they jumped out the plane... and they seemed to think less of me for not having mine already built. Whenever I pointed this out to faculty, I'd get a response like "Skydiving is supposed to be hard," or "Building a parachute is intuitive. It's your job to build it on your own," or  "Are you sure this is about peoples' parachutes? Maybe you just shouldn't have jumped," or "Maybe we don't have many skydivers like you because they just don't enjoy building parachutes as much." 

None of this sounded quite right to me, but I didn't know what to make of my experience. It took me a while to understand that: 1) the problem was the parachute policy, not me, and 2) building a parachute is easier when there are others around who have built/are currently building their own, and are willing to help you with yours.

## Application Materials

__2021/22 Cycle: Ph.D. in Political Science at MIT__

In the 2021/22 cycle, I applied to 13 Ph.D. programs: 1 in information science, 7 political science, 3 in public policy, and 2 political science joint with policy. I received 6 acceptances (1 infosci, 3 polisci, 1 public policy, 1 joint polisci/policy) and 1 waitlist. Here are my materials for the offer I accepted, but please shoot me an email if you want to see what I wrote for one of the other disciplines.

<a href="papers/CV_MIT.pdf" target="_blank" rel="noopener noreferrer" class="bi-file-earmark-pdf-fill btn btn-danger" role="button"> CV/Resume </a>
<a href="papers/SOP-MIT.pdf" target="_blank" rel="noopener noreferrer" class="bi-file-earmark-pdf-fill btn btn-primary" role="button"> Statement of Purpose</a>

<hr>

__2024/25 Cycle: Ph.D. in Sociology at Stanford__

In the 2024/25 cycle, I applied to 14 Ph.D. programs: 5 political science, 1 political science joint with policy, and 8 sociology. I received 8 acceptances (3 polisci, 1 joint polisci/policy, and 4 soc). Here are my materials for the offer I accepted, but please shoot me an email if you want to see what I wrote for one of the other disciplines. 

Note: these are structured a little different than "normal," because I had to explain why I was leaving a Ph.D. program and why I wanted to switch disciplines.

<a href="papers/CV_Stanford.pdf" target="_blank" rel="noopener noreferrer" class="bi-file-earmark-pdf-fill btn btn-danger" role="button"> CV/Resume </a>
<a href="papers/SOP-Stanford.pdf" target="_blank" rel="noopener noreferrer" class="bi-file-earmark-pdf-fill btn btn-primary" role="button"> Statement of Purpose</a>
<a href="papers/PS_Stanford.pdf" target="_blank" rel="noopener noreferrer" class="bi-file-earmark-pdf-fill btn btn-success" role="button"> Personal Statement </a>

## Reading Suggestions

In each of these boxes, I've listed some readings that either 1) helped me make sense of how my marginalized identities shaped my grad school experiences, or 2) provided me with insights into the hidden curriculum. If you get stuck behind an article's paywall, let me know and I'll try to send a link.

Note: if you are an author listed here and would like to be removed---or an author not listed here and would like to be added---please feel free to shoot me an email!

::: {.callout-note collapse="true" icon=false}

## <i class="bi bi-bookmarks"></i> &nbsp; Books
- Harris, J. L. (2024). [Black Women, Ivory Tower: Revealing the Lies of White Supremacy in American Education](https://www.drjasmineharris.com/book). Broadleaf Books.
- Lindholm, M., and Wood, E. A. (Eds.). (2024). [Between Us: Healing Ourselves and Changing the World Through Sociology](https://press.uchicago.edu/ucp/books/book/chicago/B/bo215858659.html). University of Chicago Press.
- Reyes, V. (2022). [Academic Outsider: Stories of Exclusion and Hope](https://www.sup.org/books/sociology/academic-outsider). Stanford Briefs.
- Niemann, Y. F., Gutiérrez Y Muhs, G., and Gonzalez, C. G. (2020). [Presumed Incompetent II: Race, Class, Power, and Resistance of Women in Academia](https://upcolorado.com/utah-state-university-press/item/3794-presumed-incompetent-ii). Utah State University Press.
- Ahmed, S. (2012). [On Being Included: Racism and Diversity in Institutional Life](https://www.dukeupress.edu/on-being-included). Duke University Press.
:::



::: {.callout-note collapse="true" icon=false}

## <i class="bi bi-bookmarks"></i> &nbsp; Articles
- Misra, J., Kane-Lee, E. S., Mickey, E., and Smith-Doerr, L. (2024). [“I don’t believe that I have been wanted”: Processes of Overinclusion and Exclusion in Racialized and Gendered Organizations](https://doi.org/10.1093/socpro/spae043). Social Problems.
- Spoon, K., LaBerge, N., Wapman, K. H., Zhang, S., Morgan, A. C., Galesic, M., Fosdick, B. K., Larremore, D. B., and Clauset, A. (2023). [Gender and Retention Patterns Among U.S. Faculty](https://www.science.org/doi/10.1126/sciadv.adi2205). Science Advances.
- Goodridge, L. (2022). [Professionalism as a Racial Construct](https://www.uclalawreview.org/professionalism-as-a-racial-construct/). UCLA Law Review.
- Matias, J. N., Jr., N. L., and Hope, E. (2021). [Universities Say They Want More Diverse Faculties. So Why Is Academia Still So White?](https://fivethirtyeight.com/features/universities-say-they-want-more-diverse-faculties-so-why-is-academia-still-so-white/). FiveThirtyEight.
- Key, E. M., and Sumner, J. L. (2019). [You Research Like a Girl: Gendered Research Agendas and Their Implications](https://doi.org/10.1017/S1049096519000945). PS: Political Science & Politics.
- James, A. (2017). [Sifting through the Madness: Navigating the Academy as a Black Woman PhD Student](https://activisthistory.com/2017/08/18/sifting-through-the-madness-navigating-the-academy-as-a-black-woman-phd-student/). The Activist History Review.
- McMillan Cottom, T. (2013). [Blanket “Don’t Go To Graduate School!” Advice Ignores Race and Reality?](https://tressiemc.com/uncategorized/blanket-dont-go-to-graduate-school-advice-ignores-race-and-reality/).
:::


::: {.callout-note collapse="true" icon=false}

## <i class="bi bi-bookmarks"></i> &nbsp; Blogs/Posts
- Lee, C. (2023). [Guides to Academia](https://crystaljjlee.com/blog/guides-to-academia/).
- Rucks-Ahidiana, Z. (n.d.). [Practical PhD: a transparent source for all things PhD](https://practicalphd.net/).
- Laster Pirtle, W. N. (n.d.). [theSociologyPhDandMe](https://thesociologyphdandme.wordpress.com/).
- Pacheco-Vega, R. (n.d.). [Blog](https://www.raulpacheco.org/blog/).
- Antoniak, M. (n.d.). [Advice for Academia](https://www.are.na/maria-antoniak/advice-for-academia). See also: [PhD Applications FAQ](https://maria-antoniak.github.io/2020/11/27/phd-applications.html).
- Wilson, S. (n.d.). [Advice](https://shomir.net/advice.html).
- Silvia Kim (n.d.). [Assignment Guidelines, Templates, and Research/Writing Best Practices](https://sysilviakim.com/student/).
- McAlister, M. (n.d.) [PhD Advice](https://melanimcalister.com/thinking-twice-about-grad-school/).
- Bäckman, C. (n.d.) [Resources](https://sites.google.com/view/claesbackman/tips-for-phd-students).
:::