---
title: ""
format:
  html:
    code-link: true
    toc: true
execute:
  echo: true
editor_options: 
  markdown: 
    wrap: 80
engine: knitr
---

## Overview

My personal background has greatly shaped my commitment to inclusive pedagogy and widening access to higher education. As an aspiring educator, I have actively pursued opportunities that strengthen my ability to lead equitable classrooms where students feel a sense of belonging, respect, and intellectual safety. In 2024, I earned a [Teaching Certificate](https://tll.mit.edu/programming/teaching-certificate-pathways/grad-teaching-development-tracks/) through MIT's Teaching + Learning Lab, which involved workshops in course design, inclusive teaching, lesson planning, and microteaching. In addition to this certification, I have served as a TA for three undergraduate classes.

## Teaching Assistant Experience

#### [[Fall 2024] Making Public Policy (Undergraduate)]{style="color:#005354"}

<details>
  <summary>Details (click to expand)</summary>
  <div markdown="1"
       style="margin-top:2px;
              padding:6px 6px;
              background-color:#f0f7f7;
              border:0px;
              border-radius:2px;
              display:inline-block;">
<ul style="margin:0; padding-left:1.1rem; list-style-position:outside;">
  <li><strong>Institution:</strong> Massachusetts Institute of Technology (MIT)</li>
  <li><strong>Instructor:</strong> Prof. Andrea Campbell</li>
  <li><strong>Teaching Assistant Evaluation:</strong> 6.8 out of 7</li>
  <li><strong>Student comments:</strong>
    <ul style="margin-top:4px; margin-bottom:0; padding-left:1.1rem; list-style-type:circle;">
      <li>"Ms. Webley-Brown's recitation is incredibly engaging, interactive, and supportive. She is very kind and will always be happy to help and answer questions."</li>
      <li>"Helen was both an incredible TA and such a kind person overall. Her comments helped to genuinely improve my writing and her recitations were engaging in a way that I had never experienced from a recitation before."</li>
    </ul>
  </li>
</ul>
  </div>
</details>



<hr>

#### [[Spring 2021] Quantitative Political Methodology (Undergraduate)]{style="color:#005354"}

<details>
  <summary>Details (click to expand)</summary>
  <div markdown="1"
       style="margin-top:2px;
              padding:6px 6px;
              background-color:#f0f7f7;
              border:0px;
              border-radius:2px;
              display:inline-block;">
<ul style="margin:0; padding-left:1.1rem; list-style-position:outside;">
<li><strong>Institution:</strong> Washington University in St. Louis (WashU)</li>
<li style="margin-bottom:0;"><strong>Instructor:</strong> Prof. Christopher Lucas</li>
</ul>
  </div>
</details>

<hr>

#### [[Spring 2020] Social Movements (Undergraduate)]{style="color:#005354"}

<details>
  <summary>Details (click to expand)</summary>
  <div markdown="1"
       style="margin-top:2px;
              padding:6px 6px;
              background-color:#f0f7f7;
              border:0px;
              border-radius:2px;
              display:inline-block;">
<ul style="margin:0; padding-left:1.1rem; list-style-position:outside;">
<li><strong>Institution:</strong> Washington University in St. Louis (WashU)</li>
<li style="margin-bottom:0;"><strong>Instructor:</strong> Prof. Sarah Gaby</li>
</ul>
  </div>
</details>
